# Final Words

We have finished a nice book.

If you want to split the book by sections, so each html page is a section you can use split_by='section' in the YAML header. 

```
output: 
   bookdown::gitbook:
    lib_dir: "book_assets"
    config:
      sharing: null
    split_by: section
```

## So what are all the files?

**Main files**

+ `index`. This is the main Rmd file where you can set the tile and many of the build options
+ `_bookdown.yml`. This file allows you to choose which chapters to include under which build (gitbook or pdf). You can also specify the book file name and outputs directory. 

**Chapter files**

The first three files contain all the content for your book.  The references and appendix files do not need to be changed. These ensure that you have a references section and the appendix with solutions to the tasks. Each chapter must begin with a single "#" level header (e.g. `# Introduction` at the top of the first file). 

+ `01-intro.Rmd`
+ `02-bellsandwhistles.Rmd`
+ `03-summary.Rmd`
+ `04-references.Rmd`
+ `05-ch_appendix.Rmd`

**Bibliography files**

+ `book.bib`. This .bib file is where you place your references.
+ `packages.bib`. This .bib file is created from the last part of code in the index.Rmd file.  It compiles the citations of the specified packages. 

**Style files**

+ `style.css`. This file describes the styling of the gitbook and includes they style of the "task" elements. 
+ `toc.css`. This file gives the styling for the table of contents panel to the left of the gitbook

**Git files??**

+ `DESCRIPTION`
+ `README.md`
+ `LICENCE`
+ `.gitignore`
+ `.gitattributes`

**Other files**

+ `_output.yml`  **possibly duplicates whats in the index file??**
+ `_setup.Rmd`. This file creates the "task" elements in markdown
+ `preamble.tex`. This file loads all the packages necessary for the PDF generation. It is like the preamble of a latex document.  Also defined here is how to treat the "task" elements for the PDF document. 
+ `afterbody.tex`
+ `toggle.html`
