# Applications

```{r}
library(ggplot2)
```

Some _significant_ applications are demonstrated in this chapter.

## Example one



## Example two

> **Aside**: using the model to predict outside of the range of the observed data is called **extrapolating**. Oftentimes, statistical models are developed *in order* to be used to extrapolate (e.g. climate modelling). This is however, dangerous, as we can only assess the assumptions of the model over the range of the observed data. When extrapolating we have to assume that these relationships hold beyond the range of the data, which may or may not be reasonable (hence why weather forecast over short-time periods are OK, but climate forecasts are much more uncertain). Hence, we should always view the model as an approximation of the data generating process. In this particualr case, the interpretation of the parameters is not sensible when $x = 0$ (weight = 0 kg), but makes sense in the range that we are interested in exploring. If the case where $x = 0$ is important, then we would have to change the model to ensure that the predictions made sense at those values of $x$.



```{task}

Produce a scatterplot of `mpg` against `hp`. What does the relationship look like?

```

```{solution}

``{r}
plot(hp ~ mpg, data = mtcars, 
  pch=19, col='darkgrey')
``

This is my solution

```


```{task}

This is another task with multi solution

```


```{solution, multCode = T, cache = F}

``{r, fig.height=6, fig.width=6, out.width = "60%"}
plot(hp ~ mpg, data = mtcars,
     pch=19, col='darkgrey')
``

The plot suggests that a linear relationship might exist between the two variables. So we can proceed by fitting a linear model in R.

####

``{r, fig.height=6, fig.width=6}
ggplot(mtcars) +
    geom_point(aes(x = mpg, y = hp))
``

The plot suggests that a linear relationship might exist between the two variables. So we can proceed by fitting a linear model in R.

```

